insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (1, 'Mr', 1965, 'Japan', 'Nakano', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (2, 'Honorable', 1930, 'China', 'Dianbu', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (3, 'Ms', 1995, 'Portugal', 'Gandra', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (4, 'Honorable', 1932, 'Estonia', 'Kilingi-Nõmme', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (5, 'Mr', 1963, 'Indonesia', 'Luntas', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (6, 'Mr', 1976, 'United States', 'Fullerton', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (7, 'Honorable', 1962, 'Tajikistan', 'Proletar', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (8, 'Mrs', 2011, 'South Korea', 'Yangsan', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (9, 'Rev', 2016, 'Poland', 'Żyrardów', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (10, 'Ms', 1974, 'Japan', 'Obanazawa', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (11, 'Mrs', 1943, 'Slovenia', 'Lovrenc na Pohorju', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (12, 'Dr', 2015, 'Mexico', 'San Marcos', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (13, 'Mrs', 1960, 'China', 'Xiasi', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (14, 'Mrs', 2015, 'Indonesia', 'Suruhan', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (15, 'Ms', 1930, 'Indonesia', 'Semampirbarat', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (16, 'Ms', 1984, 'Norway', 'Bergen', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (17, 'Honorable', 1999, 'Brazil', 'Laguna', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (18, 'Mrs', 1934, 'Albania', 'Orosh', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (19, 'Mrs', 2014, 'Poland', 'Targowisko', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (20, 'Mrs', 1941, 'Greece', 'Samothráki', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (21, 'Rev', 1977, 'Japan', 'Kawage', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (22, 'Dr', 1940, 'Canada', 'Donnacona', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (23, 'Dr', 2016, 'Mongolia', 'Bayanbaraat', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (24, 'Honorable', 2009, 'Portugal', 'Arneiro', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (25, 'Rev', 1982, 'Indonesia', 'Karangtalun', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (26, 'Mrs', 1984, 'Brazil', 'Piritiba', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (27, 'Honorable', 1966, 'Kenya', 'Kabarnet', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (28, 'Mr', 2012, 'Luxembourg', 'Betzdorf', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (29, 'Honorable', 1946, 'Ethiopia', 'Jinka', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (30, 'Rev', 1990, 'China', 'Yueshan', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (31, 'Mr', 1971, 'Peru', 'Socabaya', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (32, 'Mrs', 2014, 'Latvia', 'Skrunda', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (33, 'Ms', 2010, 'Indonesia', 'Sinarbakti', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (34, 'Ms', 2018, 'Indonesia', 'Karanglo', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (35, 'Rev', 2006, 'China', 'Huaping', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (36, 'Mr', 1988, 'Brazil', 'Moreno', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (37, 'Rev', 2022, 'China', 'Huangshanguan', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (38, 'Dr', 1959, 'China', 'Yanggu', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (39, 'Dr', 1941, 'Peru', 'Huancarqui', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (40, 'Ms', 2010, 'Yemen', 'Burūm', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (41, 'Honorable', 1989, 'Thailand', 'Nakhon Si Thammarat', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (42, 'Mr', 2018, 'China', 'Weizhou', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (43, 'Honorable', 1953, 'Russia', 'Kuznechnoye', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (44, 'Mr', 1950, 'China', 'Heshui', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (45, 'Ms', 1989, 'China', 'Goubangzi', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (46, 'Dr', 2001, 'China', 'Jindu', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (47, 'Rev', 1959, 'Indonesia', 'Beringinjaya', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (48, 'Rev', 1983, 'Palestinian Territory', 'Naḩḩālīn', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (49, 'Ms', 2016, 'China', 'Hongqiao', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (50, 'Dr', 1983, 'Malaysia', 'Klang', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (51, 'Dr', 2018, 'Indonesia', 'Pandak', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (52, 'Mr', 2022, 'Chile', 'Villarrica', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (53, 'Ms', 1952, 'Indonesia', 'Sukorejo', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (54, 'Dr', 2002, 'Honduras', 'Peña Blanca', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (55, 'Mrs', 1982, 'Indonesia', 'Lupak', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (56, 'Mr', 1995, 'Indonesia', 'Cayur', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (57, 'Mrs', 1930, 'Japan', 'Ōami', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (58, 'Mrs', 1947, 'China', 'Benchu', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (59, 'Dr', 1993, 'Indonesia', 'Luti', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (60, 'Ms', 1956, 'Thailand', 'Taphan Hin', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (61, 'Mr', 2010, 'Russia', 'Lesogorsk', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (62, 'Honorable', 1985, 'Slovenia', 'Kamnica', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (63, 'Dr', 1987, 'Russia', 'Sharan', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (64, 'Mr', 1930, 'Bulgaria', 'Zlataritsa', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (65, 'Ms', 1964, 'Japan', 'Chōfugaoka', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (66, 'Mrs', 1933, 'United States', 'Los Angeles', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (67, 'Ms', 1965, 'Iraq', 'As Samawah', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (68, 'Honorable', 1989, 'South Africa', 'Sundumbili', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (69, 'Honorable', 1942, 'Indonesia', 'Panggunguni', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (70, 'Mr', 1987, 'Philippines', 'Caibiran', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (71, 'Ms', 1981, 'Peru', 'Llama', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (72, 'Mr', 2010, 'Poland', 'Sławatycze', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (73, 'Rev', 1958, 'Indonesia', 'Lajaluhur', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (74, 'Honorable', 1986, 'El Salvador', 'Delgado', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (75, 'Mrs', 2003, 'New Zealand', 'Kawakawa', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (76, 'Honorable', 1935, 'Fiji', 'Nadi', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (77, 'Ms', 1942, 'Albania', 'Gurra e Vogël', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (78, 'Mrs', 1961, 'Sweden', 'Motala', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (79, 'Dr', 1967, 'Argentina', 'Florencio Varela', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (80, 'Honorable', 2018, 'Czech Republic', 'Ludgeřovice', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (81, 'Rev', 2008, 'Czech Republic', 'Želetava', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (82, 'Dr', 1994, 'Thailand', 'Nakhon Phanom', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (83, 'Ms', 1974, 'China', 'Guangming', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (84, 'Rev', 1960, 'Syria', 'Sulūk', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (85, 'Ms', 1931, 'Czech Republic', 'Mostek', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (86, 'Mrs', 1937, 'Sweden', 'Köping', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (87, 'Ms', 1970, 'Palestinian Territory', 'Jūrīsh', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (88, 'Honorable', 1956, 'Hungary', 'Budapest', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (89, 'Ms', 2021, 'Philippines', 'Anuling', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (90, 'Mr', 1957, 'China', 'Xiashu', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (91, 'Dr', 1931, 'China', 'Luoxiong', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (92, 'Mr', 1976, 'Indonesia', 'Bebae', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (93, 'Mrs', 1964, 'Indonesia', 'Sidaurip', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (94, 'Dr', 1999, 'Brazil', 'Extrema', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (95, 'Dr', 2005, 'Canada', 'Nanaimo', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (96, 'Honorable', 1938, 'China', 'Liurenba', false);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (97, 'Honorable', 1993, 'France', 'Arnage', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (98, 'Mr', 1971, 'Zimbabwe', 'Mazowe', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (99, 'Rev', 1961, 'Portugal', 'Tamel', true);
insert into tournaments (tournament_id, tournament_name, tournament_year, tournament_country, tournament_city, tournament_is_active) values (100, 'Dr', 1994, 'Sweden', 'Lycksele', true);
